FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base

FROM base AS build
WORKDIR /app
COPY . .
RUN dotnet publish Template -c Release -o out

FROM base AS final
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "Template.dll"]